export {default as partners1} from './partners1.jpg'
export {default as partners2} from './partners2.jpg'
export {default as partners3} from './partners3.jpg'
export {default as partners4} from './partners4.jpg'
export {default as partners5} from './partners5.jpg'
export {default as partners6} from './partners6.jpg'
export {default as partners7} from './partners7.jpg'
export {default as partners8} from './partners8.jpg'
export {default as partners9} from './partners9.jpg'
export {default as partners10} from './partners10.jpg'
export {default as partners11} from './partners11.jpg'
export {default as partners12} from './partners12.jpg'
export {default as partners13} from './partners13.jpg'
export {default as partners14} from './partners14.jpg'
export {default as partners15} from './partners15.jpg'
export {default as partners16} from './partners16.png'
export {default as partners18} from './partners18.png'
export {default as partners19} from './partners19.png'
export {default as partners20} from './partners20.png'
export {default as partners21} from './partners21.jpg'
export {default as partners24} from './partners24.jpg'
export {default as partners23} from './partners23.png'
export {default as partners25} from './partners25.jpg'
export {default as partners26} from './partners26.jpg'


export {default as impactimg} from './impactimg.png'
