export {default as BreadcrumbImg1} from "./breadcrumbImg1.jpg"
export {default as workpImg1} from "./workpImg1.png"
export {default as workpImg2} from "./workpImg2.jpg"
export {default as wpImg1} from "./wpImg1.jpg"
export {default as wpImg2} from "./wpImg2.jpg"
export {default as wpImg3} from "./wpImg3.jpg"
export { default as solutions1} from "./solutions1.jpg"
export {default as solutions2} from "./solutions2.jpg"
export {default as solutions3} from "./solutions3.jpg"
export {default as workslider1} from "./workslider1.svg"
export {default as workslider2} from "./workslider2.svg"
export {default as workslider3} from "./workslider3.svg"
export {default as workslider4} from "./workslider4.jpg"