
import { photo, photo1, photo2, photo3, photo4, photo5, photos } from "@/src/assets/newblogs";
import { blogArrCard } from "@/src/types";

export const  blogsArrCard= [
    {
        id:1,
        img: photo,
        title:'Introduction to the workplace marketing',
        name: 'dRSTi',
        date: 'April 18, 2023',
        Comment: '',
        content: 'Before delving into the topic, it’s important to acknowledge why corporate professionals are among the key target audiences for brands',
        btn: 'ArrowForwardIosIcon',
        cardData:{
            id:11,
            img1:photos,
            cardtitleOne:"Introduction to the workplace marketing",
            cardtitleTwo:"Now, let us know what workplace marketing is and why it is important",
            cardtitleThree:"Some key benefits of workplace marketing",
            cardtitlefour:"What dRSTi can do for you in workplace marketing? ",
            cardtitlefive:"Some of dRSTI’s key offerings",
            contentOne:"Steady income: Working professionals often have a regular and steady income, which enables them to allocate a portion of their earnings towards discretionary spending.",
            contentTwo:"Tech-savvy: Many working professionals are tech-savvy and comfortable with using technology to research and purchase products and services. They often rely on digital and technology platforms for their daily work and personal life.",
            contentThree:"Brand-conscious & aspirational: These working professionals often have strong brand preferences and may be loyal to certain brands that they trust or have had positive experiences with. They are willing to invest in products and services that they perceive as enhancing their image and status in their professional and personal lives.",
            contentFour:"Key decision-makers: Working professionals often make their own purchasing decisions, without relying on a spouse or family member to decide for them. They are more likely to make informed decisions based on their research and preferences.",
            contentFive:" Highly influential and well networked: Working professionals are highly influential individuals with well-established networks in their peer groups. Their opinions and recommendations hold significant weight and can impact the decision-making processes of their colleagues and associates.",
            contentSix:"Educated, white-collared and tax-paying audience: These working professionals are educated, white-collared, and tax-paying audiences with a high level of disposable income. They are well-informed and often seek out quality products and services that align with their values and preferences.",
            contentSeven:"Targeting working professionals can lead to increased customer loyalty, as these individuals often have the means and willingness to invest in products and services that they perceive as enhancing their personal and professional lives. By providing high-quality products and services that meet their needs and preferences, businesses can build long-term relationships with these customers, leading to repeat business and positive word-of-mouth recommendations.",
            contentEight:"Overall, by engaging with these working professionals, businesses can gather insights into what they are doing well and where they can improve. This can help businesses make informed decisions about their marketing strategies and improve their brand reputation. With such high-value professionals, businesses can enhance their brand credibility, marketing, and ultimately revenue. ",
            contentNine:"Although there are several marketing strategies available, conventional approaches may not be effective in capturing the attention of busy corporate professionals. Workplace marketing, however, is a unique approach that utilizes various marketing techniques to promote a business or brand within office spaces and actively engage with working professionals. This approach involves identifying high-traffic and highly visible areas within workspaces where brands can deliver their messages to a captive audience. Also, On-ground engagements in office spaces can help brands capture the attention of their target audience and build long-term relationships. ",
            contentTen:"Workplace marketing uses a range of mediums such as static media, digital media, and on-ground activation solutions to engage with these upscale corporate professionals in clutter-free work environments.",
            contentPone:"Captive audience: Workplace marketing provides brands with a captive audience of professionals that are challenging to reach through traditional marketing channels. By targeting these individuals at their workspace, brands can effectively capture their attention and promote their products or services.",
            contentPtwo:"High peer-to-peer interaction: Workplace marketing allows for high levels of peer-to-peer interaction, as professionals are likely to share information and experiences with their colleagues. This can help to amplify a brand's message and increase its reach. ",
            contentPthree:"Clutter-free habitats: In the workplace, individuals are often more receptive to marketing messages as they are in a clutter-free environment with fewer distractions than other spaces. This can increase the effectiveness of workplace marketing campaigns.",
            contentfour:"Showcase Your Brand: Workplace marketing offers a unique opportunity for brands to showcase their products and services in a relevant and contextual manner. By leveraging the workplace environment, brands can create targeted messaging that resonates with their audience and drives engagement",
            contentPfive:"Brand loyalty and advocacy. By engaging with working professionals in their daily work environment, brands can establish a more personal connection and build stronger relationships with their target audience. This can lead to increased brand loyalty, as well as positive word-of-mouth marketing and advocacy from satisfied customers ",
            contentPsix:"Given the significant amount of time that working professionals spend at offices and the important purchase decisions and interactions happening there, advertising in such a natural habitat can help businesses introduce their brand to new potential customers and receive valuable feedback from this critical target audience.",
            contentPseven:"Thus, Workplace marketing has proven to be a highly effective and powerful tool for businesses to reach this niche target group directly, build brand awareness, and drive revenue.",
            contentPeight:"dRSTi provides exclusive media and brand experience zones for advertising and active engagement with corporate professionals at premium workplaces, IT parks, corporate campuses, and business hubs throughout the country. With a network spanning over 150 campuses in 8 metro cities, we offer an unmatched and direct reach to more than 45 million coveted corporate audiences in India.",
            contentPnine:"Advertising Media Spaces: Strategic advertising media spaces are available in high-traffic areas like food courts, elevators, and common areas/parking lots, offering excellent branding and visibility opportunities in front of corporate professionals.",
            contentPten:"Digital OOH: A digital signage network, using IoT technology, is placed strategically throughout the corporate campus to allow for real-time and dynamic interactions with the elite audience.",
            contentP11:"Brand Activations: It includes on-ground space management for branding activations, sales kiosks, product launches, sampling activities, and other similar promotional events. This service enables businesses to effectively engage with their key target audience.",
            contentP12:"Get in touch with dRSTi to effectively target and engage with high-value, influential working professionals at their workspaces. Our extensive workplace marketing network across the country can elevate the impact of your marketing efforts and help you achieve your marketing goals.",
        }
    },
//     {
//         id:2,
//         img: photo1,
//         title:'Top 8 Principles Of Successful Digital Marketing',
//         subtitle: 'Raj Singh',
//         date: 'February 1, 2020',
//         Comment: '1 Comment',
//         content: 'You can purchase and buy ad space as well as potential customer interactions stores as Likes, Followers, and clicks to your page with the use of third parties. Mass communication has led to modern',
//         btn: 'ArrowForwardIosIcon',
//         cardData:{
//             id:21,
//             img1:photo1,
//             cardtitleOne:"Cheerful Loving Couple Bakers Drinking Coffee",
//             cardtitleTwo:"Why Integrate Side Projects?",
//             cardtitleThree:"How To Make Side Projects Work",
//             contentOne:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentTwo:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentThree:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentFour:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentFive:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentSix:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentSeven:"Targeting working professionals can lead to increased customer loyalty, as these individuals often have the means and willingness to invest in products and services that they perceive as enhancing their personal and professional lives. By providing high-quality products and services that meet their needs and preferences, businesses can build long-term relationships with these customers, leading to repeat business and positive word-of-mouth recommendations.",
//             contentEight:"Overall, by engaging with these working professionals, businesses can gather insights into what they are doing well and where they can improve. This can help businesses make informed decisions about their marketing strategies and improve their brand reputation. With such high-value professionals, businesses can enhance their brand credibility, marketing, and ultimately revenue. ",
//             contentNine:"",
//             contentTen:"",
//             contentPone:"",
//                 }
            
//         }
//     },
//  {
//         id:3,
//         img: photo2,
//         title:'Top 8 Principles Of Successful Digital Marketing',
//         subtitle: 'Ritik Singh',
//         date: 'February 1, 2020',
//         Comment: '1 Comment',
//         content: 'You can purchase and buy ad space as well as potential customer interactions stores as Likes, Followers, and clicks to your page with the use of third parties. Mass communication has led to modern',
//         btn: 'ArrowForwardIosIcon',
//         cardData:{
//             id:31,
//             img1:photo2,
//             cardtitleOne:"Cheerful Loving Couple Bakers Drinking Coffee",
//             cardtitleTwo:"Why Integrate Side Projects?",
//             cardtitleThree:"How To Make Side Projects Work",
//             contentOne:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentTwo:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentThree:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentFour:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentFive:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentSix:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentSeven:"Targeting working professionals can lead to increased customer loyalty, as these individuals often have the means and willingness to invest in products and services that they perceive as enhancing their personal and professional lives. By providing high-quality products and services that meet their needs and preferences, businesses can build long-term relationships with these customers, leading to repeat business and positive word-of-mouth recommendations.",
//             contentEight:"Overall, by engaging with these working professionals, businesses can gather insights into what they are doing well and where they can improve. This can help businesses make informed decisions about their marketing strategies and improve their brand reputation. With such high-value professionals, businesses can enhance their brand credibility, marketing, and ultimately revenue. ",
//             contentNine:"",
//             contentTen:"",
//             contentPone"",
//         }
//     },

//     {
//         id:4,
//         img: photo3,
//         title:'Top 8 Principles Of Successful Digital Marketing',
//         subtitle: 'Renu Singh',
//         date: 'February 1, 2020',
//         Comment: '1 Comment',
//         content: 'You can purchase and buy ad space as well as potential customer interactions stores as Likes, Followers, and clicks to your page with the use of third parties. Mass communication has led to modern',
//         btn: 'ArrowForwardIosIcon',
//         cardData:{
//             id:41,
//             img1:photo3,
//             cardtitleOne:"Cheerful Loving Couple Bakers Drinking Coffee",
//             cardtitleTwo:"Why Integrate Side Projects?",
//             cardtitleThree:"How To Make Side Projects Work",
//             contentOne:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentTwo:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentThree:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentFour:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentFive:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentSix:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentSeven:"Targeting working professionals can lead to increased customer loyalty, as these individuals often have the means and willingness to invest in products and services that they perceive as enhancing their personal and professional lives. By providing high-quality products and services that meet their needs and preferences, businesses can build long-term relationships with these customers, leading to repeat business and positive word-of-mouth recommendations.",
//             contentEight:"Overall, by engaging with these working professionals, businesses can gather insights into what they are doing well and where they can improve. This can help businesses make informed decisions about their marketing strategies and improve their brand reputation. With such high-value professionals, businesses can enhance their brand credibility, marketing, and ultimately revenue. ",
//             contentNine:"",
//             contentTen:"",
//             contentPone:"",

//         }
//     },

//     {
//         id:5,
//         img: photo4,
//         title:'Top 8 Principles Of Successful Digital Marketing',
//         subtitle: 'Ram Singh',
//         date: 'February 1, 2020',
//         Comment: '1 Comment',
//         content: 'You can purchase and buy ad space as well as potential customer interactions stores as Likes, Followers, and clicks to your page with the use of third parties. Mass communication has led to modern',
//         btn: 'ArrowForwardIosIcon',
//         cardData:{
//             id:51,
//             img1:photo4,
//             cardtitleOne:"Cheerful Loving Couple Bakers Drinking Coffee",
//             cardtitleTwo:"Why Integrate Side Projects?",
//             cardtitleThree:"How To Make Side Projects Work",
//             contentOne:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentTwo:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentThree:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentFour:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentFive:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentSix:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentSeven:"Targeting working professionals can lead to increased customer loyalty, as these individuals often have the means and willingness to invest in products and services that they perceive as enhancing their personal and professional lives. By providing high-quality products and services that meet their needs and preferences, businesses can build long-term relationships with these customers, leading to repeat business and positive word-of-mouth recommendations.",
//             contentEight:"Overall, by engaging with these working professionals, businesses can gather insights into what they are doing well and where they can improve. This can help businesses make informed decisions about their marketing strategies and improve their brand reputation. With such high-value professionals, businesses can enhance their brand credibility, marketing, and ultimately revenue. ",
//             contentNine:"",
//             contentTen:"",
//             contentPone"",

//         }
//     },

//     {
//         id:6,
//         img: photo5,
//         title:'Top 8 Principles Of Successful Digital Marketing',
//         subtitle: 'Rohan Singh',
//         date: 'February 1, 2020',
//         Comment: '1 Comment',
//         content: 'You can purchase and buy ad space as well as potential customer interactions stores as Likes, Followers, and clicks to your page with the use of third parties. Mass communication has led to modern',
//         btn: 'ArrowForwardIosIcon',
//         cardData:{
//             id:11,
//             img1:photo5,
//             cardtitleOne:"Cheerful Loving Couple Bakers Drinking Coffee",
//             cardtitleTwo:"Why Integrate Side Projects?",
//             cardtitleThree:"How To Make Side Projects Work",
//             contentOne:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentTwo:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentThree:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentFour:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentFive:"It’s no secret that the digital industry is booming. From exciting startups to global brands, companies are reaching out to digital agencies, responding to the new possibilities available. However, the industry is fast becoming overcrowded, heaving with agencies offering similar services — on the surface, at least.",
//             contentSix:"Producing creative, fresh projects is the key to standing out. Unique side projects are the best place to innovate, but balancing commercially and creatively lucrative work is tricky. So, this article looks at how to make side projects work and why they’re worthwhile, drawing on lessons learned from our development of the ux ompanion app.",
//             contentSeven:"Targeting working professionals can lead to increased customer loyalty, as these individuals often have the means and willingness to invest in products and services that they perceive as enhancing their personal and professional lives. By providing high-quality products and services that meet their needs and preferences, businesses can build long-term relationships with these customers, leading to repeat business and positive word-of-mouth recommendations.",
//             contentEight:"Overall, by engaging with these working professionals, businesses can gather insights into what they are doing well and where they can improve. This can help businesses make informed decisions about their marketing strategies and improve their brand reputation. With such high-value professionals, businesses can enhance their brand credibility, marketing, and ultimately revenue. ",
//             contentNine:"",
//             contentTen:"",
//             contentPone:"",
//         }
//     }

    



]